spring.application.name=exemplotestesfake
spring.datasource.url=jdbc:postgresql://ep-twilight-heart-a5i2z44q.us-east-2.aws.neon.tech/basedados?user=owner&password=Y3ZDRsKM7tad&sslmode=require
logging.level.org.hibernate.SQL=debug
